"""
docx_builder.py — Crowe-branded Deck Brief Word document assembly.

Produces deck_brief.docx from final KeystoneState after Gate 3.
Called by brief_compiler node.

Crowe brand colors:
  Dark navy:  #1B2A4A  (Heading 1)
  Navy:       #1B4F8A  (Heading 2)
  Orange:     #E87722  (accent labels)
  Dark gray:  #333333  (body text)
  Light gray: #888888  (header/footer)
"""

import io
from datetime import datetime, timezone

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor

from src.state import KeystoneState

# ── Crowe brand colors ────────────────────────────────────────────────────────
_NAVY_DARK = RGBColor(0x1B, 0x2A, 0x4A)
_NAVY = RGBColor(0x1B, 0x4F, 0x8A)
_ORANGE = RGBColor(0xE8, 0x77, 0x22)
_DARK_GRAY = RGBColor(0x33, 0x33, 0x33)
_LIGHT_GRAY = RGBColor(0x88, 0x88, 0x88)

_SECTION_LABELS = {
    "key_themes": "Key Themes",
    "pain_points": "Pain Points",
    "stated_priorities": "Stated Priorities",
    "open_questions": "Open Questions",
    "potential_recommendations": "Potential Recommendations",
    "suggested_next_steps": "Suggested Next Steps",
}


def build_docx(state: KeystoneState) -> bytes:
    """
    Assemble deck_brief.docx from final KeystoneState.
    Returns raw bytes of the .docx file.
    """
    outline = state.get("final_outline") or state.get("content_outline") or {}
    glossary = state.get("final_glossary") or state.get("acronym_glossary") or []
    context = state.get("client_context_profile") or {}

    doc = Document()
    _set_margins(doc)
    _add_header_footer(doc, state)

    # ── Title ─────────────────────────────────────────────────────────────────
    title = doc.add_heading(f"Deck Brief: {state.get('client_name', 'Client')}", level=0)
    title.runs[0].font.color.rgb = _NAVY_DARK
    title.runs[0].font.size = Pt(22)

    subtitle = doc.add_paragraph(
        f"{state.get('client_industry', '')}  |  "
        f"Generated by Keystone  |  "
        f"{datetime.now(tz=timezone.utc).strftime('%B %d, %Y')}"
    )
    subtitle.runs[0].font.color.rgb = _LIGHT_GRAY
    subtitle.runs[0].font.size = Pt(10)
    doc.add_paragraph()

    # ── Section 1: Client Context ─────────────────────────────────────────────
    _heading1(doc, "1. Client Context")

    if context.get("summary"):
        _body(doc, context["summary"])

    if context.get("key_facts"):
        _heading2(doc, "Key Facts")
        for fact in context["key_facts"]:
            doc.add_paragraph(fact, style="List Bullet")

    if context.get("regulatory_environment"):
        _heading2(doc, "Regulatory Environment")
        _body(doc, context["regulatory_environment"])

    if context.get("recent_news"):
        _heading2(doc, "Recent Developments")
        for news in context["recent_news"]:
            doc.add_paragraph(news, style="List Bullet")

    doc.add_paragraph()

    # ── Section 2: Acronym Glossary ───────────────────────────────────────────
    if glossary:
        _heading1(doc, "2. Acronym Glossary")
        table = doc.add_table(rows=1, cols=2)
        table.style = "Table Grid"
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = "Term"
        hdr_cells[1].text = "Expansion"
        for cell in hdr_cells:
            _set_cell_bg(cell, "1B2A4A")
            for run in cell.paragraphs[0].runs:
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.bold = True

        for entry in glossary:
            if isinstance(entry, dict):
                term = entry.get("term", "")
                expansion = entry.get("expansion", "")
            else:
                term = getattr(entry, "term", "")
                expansion = getattr(entry, "expansion", "")
            row = table.add_row().cells
            row[0].text = term
            row[1].text = expansion

        doc.add_paragraph()

    # ── Section 3: Discovery Findings ─────────────────────────────────────────
    _heading1(doc, "3. Discovery Findings")

    section_num = 1
    for section_key, label in _SECTION_LABELS.items():
        items = outline.get(section_key, [])
        if not items:
            continue

        _heading2(doc, f"3.{section_num} {label}")
        section_num += 1

        for item in items:
            # Item text as bullet
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(item.get("text", ""))
            run.font.color.rgb = _DARK_GRAY
            run.font.size = Pt(11)

            # Source quote in smaller italic
            source = item.get("source_quote", "")
            if source:
                sq = doc.add_paragraph()
                sq.paragraph_format.left_indent = Cm(1.0)
                r = sq.add_run(f'"{source}"')
                r.font.italic = True
                r.font.size = Pt(9)
                r.font.color.rgb = _LIGHT_GRAY

            # Slide type hint if present
            hint = item.get("slide_type_hint")
            if hint:
                hp = doc.add_paragraph()
                hp.paragraph_format.left_indent = Cm(1.0)
                hr = hp.add_run(f"Suggested slide type: {hint}")
                hr.font.size = Pt(9)
                hr.font.color.rgb = _ORANGE

        doc.add_paragraph()

    # ── Section 4: Deck Structure Recommendation ──────────────────────────────
    _heading1(doc, "4. Recommended Deck Structure")

    total_items = sum(len(outline.get(k, [])) for k in _SECTION_LABELS)
    slide_count = max(10, min(15, 2 + (total_items // 2) + 2))
    _body(doc, f"Suggested slide count: {slide_count} slides")
    _body(doc, "Narrative arc: Context → Challenges & Priorities → Findings → Recommendations → Next Steps")

    doc.add_paragraph()
    _body(doc, "This document is a human-review artifact. The corresponding deck_handoff.json file is used by Claude Code to begin deck generation.")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── Helpers ───────────────────────────────────────────────────────────────────

def _set_margins(doc: Document) -> None:
    for section in doc.sections:
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin = Cm(2.54)
        section.right_margin = Cm(2.54)


def _add_header_footer(doc: Document, state: KeystoneState) -> None:
    section = doc.sections[0]

    # Header
    header = section.header
    header.is_linked_to_previous = False
    hp = header.paragraphs[0]
    hp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = hp.add_run("CONFIDENTIAL — INTERNAL USE ONLY")
    run.font.size = Pt(8)
    run.font.color.rgb = _LIGHT_GRAY

    # Footer
    footer = section.footer
    footer.is_linked_to_previous = False
    fp = footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.LEFT
    r_left = fp.add_run("Crowe LLP — Keystone Deck Brief")
    r_left.font.size = Pt(8)
    r_left.font.color.rgb = _LIGHT_GRAY

    # Page number field (right-aligned via tab)
    fp.add_run("\t\t")
    _add_page_number_field(fp)


def _add_page_number_field(paragraph) -> None:
    """Add {PAGE} field to a paragraph for auto page numbering."""
    run = paragraph.add_run()
    fld_char1 = OxmlElement("w:fldChar")
    fld_char1.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.text = " PAGE "
    fld_char2 = OxmlElement("w:fldChar")
    fld_char2.set(qn("w:fldCharType"), "end")
    run._r.append(fld_char1)
    run._r.append(instr)
    run._r.append(fld_char2)
    run.font.size = Pt(8)
    run.font.color.rgb = _LIGHT_GRAY


def _set_cell_bg(cell, hex_color: str) -> None:
    """Set table cell background color via OOXML."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _heading1(doc: Document, text: str) -> None:
    h = doc.add_heading(text, level=1)
    if h.runs:
        h.runs[0].font.color.rgb = _NAVY_DARK
        h.runs[0].font.size = Pt(16)


def _heading2(doc: Document, text: str) -> None:
    h = doc.add_heading(text, level=2)
    if h.runs:
        h.runs[0].font.color.rgb = _NAVY
        h.runs[0].font.size = Pt(13)


def _body(doc: Document, text: str) -> None:
    p = doc.add_paragraph(text)
    if p.runs:
        p.runs[0].font.color.rgb = _DARK_GRAY
        p.runs[0].font.size = Pt(11)
